### ISSUE TITLE
bug:  TRPC Calls from RSC cause Next to throw dynamic server error

### ISSUE THREAD

**Issue by rydonahue1** [t3-oss/create-t3-app#1726]
### Provide environment information

 System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 49.60 GB / 63.21 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD

### Describe the bug

Noticed this error get thrown when starting up a base T3 app and then running build right away

```
 Generating static pages (0/4)  [=   ]y [TRPCClientError]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at y.from (C:\Code\planetscale-debug\.next\server\app\page.js:1:26283)
    at C:\Code\planetscale-debug\.next\server\app\page.js:5:1636 {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at s (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:4931)
      at d (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:2674)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:4476
      at C:\Code\planetscale-debug\node_modules\.pnpm\next@14.0.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:179176
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5411
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:5:5185)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5313
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:881 {
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
y [TRPCClientError]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at y.from (C:\Code\planetscale-debug\.next\server\app\page.js:1:26283)
    at C:\Code\planetscale-debug\.next\server\app\page.js:5:1636 {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: n [Error]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at s (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:4931)
      at d (C:\Code\planetscale-debug\.next\server\chunks\362.js:1:2674)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:4476
      at C:\Code\planetscale-debug\node_modules\.pnpm\next@14.0.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:179176
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5411
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:5:5185)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:5313
      at Object.subscribe (C:\Code\planetscale-debug\.next\server\app\page.js:1:25129)
      at C:\Code\planetscale-debug\.next\server\app\page.js:5:881 {
    digest: 'DYNAMIC_SERVER_USAGE'
  }
}
```

### Reproduction repo

https://github.com/t3-oss/create-t3-app

### To reproduce

Created t3 app with trpc, drizzle and pg or planetscale then run build command (also occurs with pnpm as well).

### Additional information

The error is preventable by adding `export const dynamic = "force-dynamic"` or calling  `cookies()` before the api call within the RSC.

Alternatively not passing the cookies to the TRPC Provider also appears to work, I am just not sure how this would effect T3 stack.

Since neither of the mentioned work  arounds were included with the stack, I am assuming something must have changed with a release of Next to cause the build errors. But if they are the correct approach, feel free to let me know. Thanks!

**Comment by juliusmarminge** [comment]
Should be fixed

**Comment by rydonahue1** [comment]
> Should be fixed

Correct me if I am wrong but I think this still appears to require a `no_store` call above every RSC with a TRPC call within it? I feel that could be an easy line to overlook and wind up with a failed deploy.

Not sure if this is the best solution, and I think this is more something next should fix with their compiler in the future since everything technically works fine except for the build process complaining.

But in the meantime I wrapped my TRPC api with a function that requires the headers from the RSC to be passed in, that way you can not accidentally forget.

So your TRPC api call ends up looking like this:
```ts
api(headers()).router.procedure.query();
```

Thoughts?

**Comment by deltasierra96** [comment]
Any updates on this issue? Seems to be something that's largely being ignored.

**Comment by ishaqyusuf** [comment]
Any update on it? this still happens in most recent clone.

**Comment by zrthomas** [comment]
This issue still persists in trpc 11. Is there a solution that preserves static/ISR capabilities while allowing trpc calls in server components?  calling nostore or cookies seems like a band-aid solution.

**Comment by antonius-dev** [comment]
Still have this error

**Comment by eubieald** [comment]
can still replicate this error in trpc 11.
